# Generated by Django 6.1.1 on 2026-09-20 16:26

import apps.common.fields
import apps.common.upload
import apps.common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('custom_cake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='۱۱ تا ۱۳', max_length=40, verbose_name='عنوان')),
                ('start_time', models.TimeField(verbose_name='از ساعت')),
                ('end_time', models.TimeField(verbose_name='تا ساعت')),
                ('weekday', models.SmallIntegerField(blank=True, help_text='خالی یعنی همه\u200cی روزها. ۰ شنبه تا ۶ جمعه.', null=True, verbose_name='روز هفته')),
                ('capacity', models.SmallIntegerField(default=10, verbose_name='ظرفیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'بازه تحویل',
                'verbose_name_plural': 'بازه\u200cهای تحویل',
                'ordering': ('sort_order', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='توضیح')),
                ('kind', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=10, verbose_name='نوع')),
                ('value', models.IntegerField(help_text='برای درصدی عدد ۱ تا ۱۰۰؛ برای مبلغ ثابت، ریال.', verbose_name='مقدار')),
                ('min_order_rial', models.BigIntegerField(default=0, verbose_name='حداقل مبلغ سفارش (ریال)')),
                ('max_discount_rial', models.BigIntegerField(blank=True, help_text='برای تخفیف درصدی حتماً پر شود.', null=True, verbose_name='سقف تخفیف (ریال)')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('total_limit', models.IntegerField(blank=True, null=True, verbose_name='سقف کل استفاده')),
                ('per_user_limit', models.SmallIntegerField(default=1, verbose_name='سقف هر کاربر')),
                ('used_count', models.IntegerField(default=0, verbose_name='تعداد استفاده')),
                ('first_order_only', models.BooleanField(default=False, verbose_name='فقط اولین سفارش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='کلید نشست')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('message_on_cake', models.CharField(blank=True, max_length=60, verbose_name='نوشته روی کیک')),
                ('quantity', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('addons', models.ManyToManyField(blank=True, to='catalog.productaddon', verbose_name='افزودنی\u200cها')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='سبد')),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productflavor', verbose_name='طعم')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productsize', verbose_name='اندازه')),
            ],
            options={
                'verbose_name': 'قلم سبد',
                'verbose_name_plural': 'اقلام سبد',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='کد سفارش')),
                ('customer_name', models.CharField(max_length=120, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(db_index=True, max_length=11, validators=[apps.common.validators.validate_phone], verbose_name='شماره مشتری')),
                ('method', models.CharField(choices=[('pickup', 'تحویل حضوری'), ('courier', 'ارسال با پیک')], default='pickup', max_length=10, verbose_name='روش تحویل')),
                ('address_snapshot', apps.common.fields.JSONField(blank=True, default=dict, verbose_name='نشانی (اسنپ\u200cشات)')),
                ('due_date', models.DateField(db_index=True, verbose_name='تاریخ تحویل')),
                ('fulfillment_status', models.CharField(choices=[('new', 'ثبت شد'), ('baking', 'در حال پخت'), ('ready', 'آماده'), ('delivered', 'تحویل شد'), ('canceled', 'لغو شد')], db_index=True, default='new', max_length=12, verbose_name='وضعیت آماده\u200cسازی')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('deposit', 'بیعانه'), ('paid', 'پرداخت شده'), ('refunded', 'بازگشت داده شد'), ('failed', 'ناموفق')], db_index=True, default='unpaid', max_length=10, verbose_name='وضعیت پرداخت')),
                ('pay_method', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('onsite', 'پرداخت در محل')], default='online', max_length=10, verbose_name='روش پرداخت')),
                ('items_total_rial', models.BigIntegerField(default=0, verbose_name='جمع اقلام (ریال)')),
                ('discount_rial', models.BigIntegerField(default=0, verbose_name='تخفیف (ریال)')),
                ('delivery_fee_rial', models.BigIntegerField(default=0, verbose_name='هزینه ارسال (ریال)')),
                ('gift_wrap_rial', models.BigIntegerField(default=0, verbose_name='بسته هدیه (ریال)')),
                ('vat_rial', models.BigIntegerField(default=0, verbose_name='مالیات (ریال)')),
                ('grand_total_rial', models.BigIntegerField(default=0, verbose_name='مبلغ نهایی (ریال)')),
                ('paid_rial', models.BigIntegerField(default=0, verbose_name='پرداخت\u200cشده (ریال)')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ مالیات')),
                ('gift_wrap', models.BooleanField(default=False, verbose_name='بسته\u200cبندی هدیه')),
                ('gift_message', models.TextField(blank=True, verbose_name='پیام کارت هدیه')),
                ('allergy_note', models.TextField(blank=True, help_text='روی کارت تابلو با هشدار قرمز نشان داده می\u200cشود.', verbose_name='حساسیت غذایی')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('staff_note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('placed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آماده شدن')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل لغو')),
                ('version', models.IntegerField(default=1, verbose_name='نسخه')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_orders', to=settings.AUTH_USER_MODEL, verbose_name='لغو توسط')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryslot', verbose_name='بازه تحویل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='کد تخفیف')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-placed_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('catalogue', 'ویترین'), ('custom', 'سفارشی')], default='catalogue', max_length=10, verbose_name='نوع')),
                ('name', models.CharField(max_length=140, verbose_name='نام')),
                ('size_label', models.CharField(blank=True, max_length=80, verbose_name='اندازه')),
                ('flavor_label', models.CharField(blank=True, max_length=80, verbose_name='طعم')),
                ('image', apps.common.fields.ImageField(blank=True, help_text='اسنپ\u200cشات تصویر؛ محصول ممکن است سال\u200cها بعد عوض شود.', upload_to=apps.common.upload.UploadTo('orders/items'), verbose_name='تصویر')),
                ('message_on_cake', models.CharField(blank=True, help_text='«روی کیک نوشته شود: …» — write در orders-data.js', max_length=60, verbose_name='نوشته روی کیک')),
                ('quantity', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price_rial', models.BigIntegerField(verbose_name='قیمت واحد (ریال)')),
                ('line_total_rial', models.BigIntegerField(verbose_name='جمع ردیف (ریال)')),
                ('custom_cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='custom_cake.customcakerequest', verbose_name='کیک اختصاصی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItemSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='برچسب')),
                ('value', models.CharField(max_length=300, verbose_name='مقدار')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='ترتیب')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='orders.orderitem', verbose_name='قلم')),
            ],
            options={
                'verbose_name': 'مشخصه قلم',
                'verbose_name_plural': 'مشخصات قلم',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('fulfillment', 'آماده\u200cسازی'), ('payment', 'پرداخت')], default='fulfillment', max_length=12, verbose_name='ستون')),
                ('from_value', models.CharField(blank=True, max_length=12, verbose_name='از')),
                ('to_value', models.CharField(max_length=12, verbose_name='به')),
                ('is_reverse', models.BooleanField(default=False, verbose_name='بازگشت به عقب')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_changes', to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تغییر وضعیت',
                'verbose_name_plural': 'تاریخچه وضعیت',
                'ordering': ('changed_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('session_key', ''), _negated=True), _connector='OR'), name='cart_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cartitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='orderitem_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fulfillment_status', 'due_date'], name='order_board_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-placed_at'], name='order_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-placed_at'], name='order_pay_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('fulfillment_status__in', ['delivered', 'canceled']), _negated=True), fields=['due_date'], name='order_open_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total_rial__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('paid_rial__gte', 0)), name='order_paid_non_negative'),
        ),
    ]
