# Generated by Django 6.1.1 on 2026-09-20 16:26

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=40, verbose_name='شماره/نام کاربری')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='مرورگر')),
                ('is_staff_panel', models.BooleanField(default=False, verbose_name='ورود کارکنان')),
                ('succeeded', models.BooleanField(default=False, verbose_name='موفق')),
                ('failure_reason', models.CharField(blank=True, max_length=40, verbose_name='دلیل ناموفقی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'تلاش ورود',
                'verbose_name_plural': 'تلاش\u200cهای ورود',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('signup', 'ثبت\u200cنام'), ('reset', 'بازیابی رمز'), ('change_phone', 'تغییر شماره')], default='login', max_length=16, verbose_name='کاربرد')),
                ('code_hash', models.CharField(max_length=128, verbose_name='هش کد')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='انقضا')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده')),
                ('attempts', models.SmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'کد یک\u200cبارمصرف',
                'verbose_name_plural': 'کدهای یک\u200cبارمصرف',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('phone', models.CharField(help_text='با ۰۹ شروع می\u200cشود. همین شناسه\u200cی ورود است.', max_length=11, unique=True, validators=[apps.common.validators.validate_phone], verbose_name='شماره موبایل')),
                ('username', models.CharField(blank=True, help_text='فقط برای کارکنان.', max_length=40, null=True, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('birth_year', models.SmallIntegerField(blank=True, null=True, verbose_name='سال تولد')),
                ('birth_month', models.SmallIntegerField(blank=True, db_index=True, null=True, verbose_name='ماه تولد')),
                ('birth_day', models.SmallIntegerField(blank=True, db_index=True, null=True, verbose_name='روز تولد')),
                ('role', models.CharField(choices=[('customer', 'مشتری'), ('kitchen', 'ادمین قنادی'), ('manager', 'مدیر')], db_index=True, default='customer', max_length=12, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, help_text='این با «نقش» فرق دارد؛ فقط ورود به /admin/ را کنترل می\u200cکند.', verbose_name='دسترسی به پنل جنگو')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='شماره تأیید شده')),
                ('sms_opt_in', models.BooleanField(default=True, verbose_name='اطلاع\u200cرسانی پیامکی')),
                ('email_opt_in', models.BooleanField(default=False, verbose_name='خبرنامه')),
                ('orders_count', models.IntegerField(default=0, verbose_name='تعداد سفارش')),
                ('total_spent_rial', models.BigIntegerField(default=0, verbose_name='مجموع خرید (ریال)')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین سفارش')),
                ('totp_secret', models.CharField(blank=True, max_length=64, verbose_name='کلید دومرحله\u200cای')),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='دومرحله\u200cای فعال')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ناشناس\u200cسازی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان حذف')),
                ('title', models.CharField(help_text='خانه · محل کار', max_length=40, verbose_name='عنوان')),
                ('receiver_name', models.CharField(max_length=80, verbose_name='تحویل\u200cگیرنده')),
                ('receiver_phone', models.CharField(max_length=11, validators=[apps.common.validators.validate_phone], verbose_name='شماره تحویل\u200cگیرنده')),
                ('province', models.CharField(default='خراسان رضوی', max_length=40, verbose_name='استان')),
                ('city', models.CharField(default='مشهد', max_length=40, verbose_name='شهر')),
                ('district', models.CharField(blank=True, max_length=60, verbose_name='محله')),
                ('line', models.CharField(max_length=300, verbose_name='نشانی')),
                ('plaque', models.CharField(blank=True, max_length=12, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=12, verbose_name='واحد')),
                ('postal_code', models.CharField(blank=True, max_length=10, validators=[apps.common.validators.validate_postal_code], verbose_name='کد پستی')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نشانی',
                'verbose_name_plural': 'نشانی\u200cها',
                'ordering': ('-is_default', '-created_at'),
            },
        ),
    ]
