# Generated by Django 6.1.1 on 2026-09-20 16:26

import apps.common.fields
import apps.common.upload
import apps.common.validators
import apps.custom_cake.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('label', models.CharField(max_length=60, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='توضیح')),
                ('price_delta_rial', models.BigIntegerField(default=0, verbose_name='اختلاف قیمت (ریال)')),
            ],
            options={
                'verbose_name': 'روکش',
                'verbose_name_plural': 'روکش\u200cها',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CakeFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('label', models.CharField(max_length=60, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='توضیح')),
                ('price_delta_rial', models.BigIntegerField(default=0, verbose_name='اختلاف قیمت (ریال)')),
            ],
            options={
                'verbose_name': 'فیلینگ',
                'verbose_name_plural': 'فیلینگ\u200cها',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CakeFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('label', models.CharField(max_length=60, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='توضیح')),
                ('price_delta_rial', models.BigIntegerField(default=0, verbose_name='اختلاف قیمت (ریال)')),
            ],
            options={
                'verbose_name': 'طعم کیک اختصاصی',
                'verbose_name_plural': 'طعم\u200cهای کیک اختصاصی',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CakeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('label', models.CharField(max_length=60, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='توضیح')),
                ('price_delta_rial', models.BigIntegerField(default=0, verbose_name='اختلاف قیمت (ریال)')),
                ('base_price_rial', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پایه (ریال)')),
                ('serves', models.CharField(help_text='۱۲ تا ۱۵ نفر', max_length=60, verbose_name='تعداد نفرات')),
                ('approx_weight', models.CharField(blank=True, help_text='حدود ۴ کیلو', max_length=40, verbose_name='وزن تقریبی')),
                ('max_tiers', models.SmallIntegerField(default=1, verbose_name='حداکثر طبقه')),
            ],
            options={
                'verbose_name': 'اندازه کیک اختصاصی',
                'verbose_name_plural': 'اندازه\u200cهای کیک اختصاصی',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CakeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('version', models.CharField(default='1', max_length=20, verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'بند شرایط',
                'verbose_name_plural': 'شرایط کیک اختصاصی',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CustomCakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.common.fields.ImageField(storage=apps.custom_cake.models.private_storage, upload_to=apps.common.upload.UploadTo('custom-cake'), validators=[apps.common.validators.MaxFileSize(5)], verbose_name='تصویر')),
                ('kind', models.CharField(choices=[('reference', 'عکس نمونه'), ('print', 'عکس چاپ روی کیک')], default='reference', max_length=10, verbose_name='نوع')),
                ('caption', models.CharField(blank=True, help_text='refNote یا printNote — «مشتری گفت: …»', max_length=200, verbose_name='یادداشت')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='ترتیب')),
                ('content_type', models.CharField(blank=True, max_length=60, verbose_name='نوع فایل')),
                ('size_bytes', models.IntegerField(default=0, verbose_name='حجم')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
            ],
            options={
                'verbose_name': 'تصویر کیک اختصاصی',
                'verbose_name_plural': 'تصاویر کیک اختصاصی',
                'ordering': ('kind', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CustomCakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='کد درخواست')),
                ('contact_name', models.CharField(max_length=60, verbose_name='نام')),
                ('contact_family', models.CharField(max_length=60, verbose_name='نام خانوادگی')),
                ('contact_phone', models.CharField(db_index=True, max_length=11, validators=[apps.common.validators.validate_phone], verbose_name='شماره تماس')),
                ('contact_phone_alt', models.CharField(blank=True, max_length=11, validators=[apps.common.validators.validate_phone], verbose_name='شماره دوم')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('mode', models.CharField(choices=[('reference', 'طرح نمونه'), ('print', 'چاپ عکس خوراکی')], default='reference', max_length=10, verbose_name='حالت')),
                ('tiers', models.SmallIntegerField(default=1, verbose_name='تعداد طبقه')),
                ('color_theme', models.CharField(blank=True, max_length=80, verbose_name='رنگ غالب')),
                ('message_on_cake', models.CharField(blank=True, help_text='حداکثر ۳۰ نویسه — همان سقف ویزارد.', max_length=30, verbose_name='نوشته روی کیک')),
                ('design_note', models.TextField(blank=True, help_text='مثل عکس باشد ولی رنگ روبان\u200cها صورتی…', verbose_name='توضیح طرح')),
                ('allergy_note', models.TextField(blank=True, verbose_name='حساسیت غذایی')),
                ('event_date', models.DateField(db_index=True, help_text='حداقل سه روز بعد. این شرط باید در سرور هم بررسی شود، نه فقط در تقویم.', verbose_name='تاریخ مراسم')),
                ('estimate_min_rial', models.BigIntegerField(default=0, verbose_name='حداقل برآورد (ریال)')),
                ('estimate_max_rial', models.BigIntegerField(default=0, verbose_name='حداکثر برآورد (ریال)')),
                ('quoted_price_rial', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت اعلام\u200cشده (ریال)')),
                ('deposit_rial', models.BigIntegerField(default=0, help_text='خالی بماند تا از جدول نرخ\u200cها برداشته شود.', verbose_name='بیعانه (ریال)')),
                ('print_fee_rial', models.BigIntegerField(default=0, help_text='فقط در حالت «چاپ عکس خوراکی».', verbose_name='هزینه چاپ (ریال)')),
                ('status', models.CharField(choices=[('submitted', 'ثبت شد'), ('reviewing', 'در حال بررسی'), ('quoted', 'قیمت اعلام شد'), ('approved', 'تأیید مشتری'), ('converted', 'تبدیل به سفارش'), ('rejected', 'رد شد'), ('canceled', 'لغو شد')], db_index=True, default='submitted', max_length=12, verbose_name='وضعیت')),
                ('staff_note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('cancel_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت لغو')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پذیرش شرایط')),
                ('terms_version', models.CharField(blank=True, max_length=20, verbose_name='نسخه شرایط')),
                ('coating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='custom_cake.cakecoating', verbose_name='روکش')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='custom_cake.cakefilling', verbose_name='فیلینگ')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='custom_cake.cakeflavor', verbose_name='طعم')),
                ('occasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cake_requests', to='catalog.occasion', verbose_name='مناسبت')),
            ],
            options={
                'verbose_name': 'درخواست کیک اختصاصی',
                'verbose_name_plural': 'درخواست\u200cهای کیک اختصاصی',
                'ordering': ('-created_at',),
            },
        ),
    ]
