# Generated by Django 6.1.1 on 2026-09-20 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_cake', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakerequest',
            name='order',
            field=models.ForeignKey(blank=True, help_text='وقتی پر می\u200cشود که درخواست به سفارش تبدیل شده باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cake_requests', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cake_requests', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='custom_cake.cakesize', verbose_name='اندازه'),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cake_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='customcakeimage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='custom_cake.customcakerequest', verbose_name='درخواست'),
        ),
        migrations.AddIndex(
            model_name='customcakerequest',
            index=models.Index(fields=['status', 'event_date'], name='cakereq_status_idx'),
        ),
    ]
