# Generated by Django 6.1.1 on 2026-09-20 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_cake', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('kind', models.CharField(choices=[('new_order', 'سفارش جدید'), ('cake_request', 'درخواست کیک اختصاصی'), ('payment', 'پرداخت'), ('overdue', 'سفارش عقب\u200cافتاده'), ('canceled', 'لغو سفارش'), ('system', 'سیستمی')], default='system', max_length=16, verbose_name='نوع')),
                ('title', models.CharField(max_length=140, verbose_name='عنوان')),
                ('body', models.CharField(blank=True, max_length=300, verbose_name='متن')),
                ('target_roles', models.CharField(default='kitchen,manager', help_text='با کاما جدا کنید: kitchen,manager', max_length=60, verbose_name='نقش\u200cهای مخاطب')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='فوری')),
                ('cake_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='custom_cake.customcakerequest', verbose_name='درخواست کیک')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order', verbose_name='سفارش')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seen_notifications', to=settings.AUTH_USER_MODEL, verbose_name='دیده شده توسط')),
            ],
            options={
                'verbose_name': 'اعلان پنل',
                'verbose_name_plural': 'اعلان\u200cهای پنل',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at', 'kind'], name='notif_recent_idx')],
            },
        ),
    ]
