# Generated by Django 6.1.1 on 2026-09-20 16:26

import apps.common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('transfer', 'کارت به کارت')], default='zarinpal', max_length=12, verbose_name='کانال دریافت')),
                ('kind', models.CharField(choices=[('full', 'پرداخت کامل'), ('deposit', 'بیعانه'), ('settlement', 'تسویه مانده'), ('refund', 'بازگشت وجه')], default='full', max_length=12, verbose_name='نوع')),
                ('amount_rial', models.BigIntegerField(verbose_name='مبلغ (ریال)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('succeeded', 'موفق'), ('failed', 'ناموفق'), ('canceled', 'لغو شده')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='شناسه تراکنش درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=80, verbose_name='کد پیگیری')),
                ('card_pan', models.CharField(blank=True, max_length=24, verbose_name='شماره کارت (ماسک\u200cشده)')),
                ('raw_response', apps.common.fields.JSONField(blank=True, default=dict, verbose_name='پاسخ درگاه')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('note', models.CharField(blank=True, help_text='برای بازگشت وجه، دلیلش را اینجا بنویسید.', max_length=200, verbose_name='توضیح')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت توسط')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['order', 'status'], name='payment_order_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ref_id__gt', '')), fields=('gateway', 'ref_id'), name='payment_ref_unique')],
            },
        ),
    ]
