# Generated by Django 6.1.1 on 2026-09-22 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0002_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='custom_cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='custom_cake.customcakerequest', verbose_name='درخواست کیک اختصاصی'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('transfer', 'کارت به کارت'), ('sandbox', 'بدون درگاه (آزمایشی)')], default='zarinpal', max_length=12, verbose_name='کانال دریافت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['custom_cake', 'status'], name='payment_cake_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_cake__isnull', True), ('order__isnull', False)), models.Q(('custom_cake__isnull', False), ('order__isnull', True)), _connector='OR'), name='payment_has_one_owner'),
        ),
    ]
