# Generated by Django 6.1.1 on 2026-09-20 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_enabled', models.BooleanField(default=False, help_text='تا وقتی خاموش است، در ثبت سفارش فقط تحویل حضوری دیده می\u200cشود.', verbose_name='ارسال با پیک فعال')),
                ('delivery_fee_rial', models.BigIntegerField(default=650000, verbose_name='هزینه ارسال (ریال)')),
                ('free_delivery_over_rial', models.BigIntegerField(default=15000000, verbose_name='ارسال رایگان از (ریال)')),
                ('gift_wrap_rial', models.BigIntegerField(default=850000, verbose_name='بسته هدیه (ریال)')),
                ('custom_deposit_rial', models.BigIntegerField(default=4000000, verbose_name='بیعانه کیک اختصاصی (ریال)')),
                ('custom_print_fee_rial', models.BigIntegerField(default=2500000, verbose_name='هزینه چاپ عکس خوراکی (ریال)')),
                ('vat_enabled', models.BooleanField(default=False, verbose_name='محاسبه مالیات')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نرخ مالیات (٪)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'نرخ\u200cها',
                'verbose_name_plural': 'نرخ\u200cها',
            },
        ),
    ]
