# Generated by Django 6.1.1 on 2026-09-20 16:26

import apps.common.fields
import apps.common.upload
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('image', apps.common.fields.ImageField(upload_to=apps.common.upload.UploadTo('catalog/gallery'), verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=140, verbose_name='متن جایگزین')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='عنوان')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری',
                'ordering': ('sort_order', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نشانی')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکن')),
            ],
            options={
                'verbose_name': 'مناسبت',
                'verbose_name_plural': 'مناسبت\u200cها',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نشانی')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='آیکن')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('slug', models.SlugField(allow_unicode=True, max_length=60, unique=True, verbose_name='نشانی')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('name_en', models.CharField(blank=True, max_length=60, verbose_name='نام لاتین')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('image', apps.common.fields.ImageField(blank=True, upload_to=apps.common.upload.UploadTo('catalog/categories'), verbose_name='تصویر')),
                ('show_in_megamenu', models.BooleanField(default=True, verbose_name='نمایش در مگامنو')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه\u200cی اصلی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='دسته\u200cی مادر')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته\u200cها',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='خالی بگذارید تا از نام لاتین ساخته شود.', max_length=80, unique=True, verbose_name='نشانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام لاتین')),
                ('price_rial', models.BigIntegerField(help_text='به ریال وارد کنید. در سایت تومان نمایش داده می\u200cشود.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (ریال)')),
                ('compare_at_price_rial', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پیش از تخفیف (ریال)')),
                ('short_description', models.CharField(blank=True, help_text='بخش\u200cها را با « · » جدا کنید؛ کارت محصول همان\u200cجا می\u200cشکندش.', max_length=200, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('serves', models.CharField(blank=True, help_text='۶ تا ۸ نفر · پک ۶ عددی · حدود ۱٫۵ کیلو', max_length=60, verbose_name='اندازه')),
                ('badge', models.CharField(blank=True, choices=[('', '—'), ('bestseller', 'پرفروش'), ('new', 'تازه'), ('seasonal', 'فصلی'), ('limited', 'محدود')], max_length=12, verbose_name='نشان')),
                ('ingredients', models.TextField(blank=True, verbose_name='مواد اولیه')),
                ('allergens', models.TextField(blank=True, verbose_name='هشدار حساسیت')),
                ('keeping', models.TextField(blank=True, verbose_name='نگهداری')),
                ('rating', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3, verbose_name='امتیاز')),
                ('reviews_count', models.IntegerField(default=0, editable=False, verbose_name='تعداد نظر')),
                ('prep_days', models.SmallIntegerField(default=0, help_text='حداقل فاصله تا تحویل. صفر یعنی همان روز.', verbose_name='روز آماده\u200cسازی')),
                ('in_stock', models.BooleanField(default=True, help_text='ادمین قنادی فقط همین را می\u200cتواند تغییر دهد.', verbose_name='موجود')),
                ('sales_count', models.IntegerField(db_index=True, default=0, verbose_name='تعداد فروش')),
                ('search_norm', models.TextField(blank=True, editable=False, verbose_name='نمایه\u200cی جست\u200cوجو')),
                ('meta_title', models.CharField(blank=True, max_length=120, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, max_length=200, verbose_name='توضیح سئو')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته')),
                ('occasions', models.ManyToManyField(blank=True, related_name='products', to='catalog.occasion', verbose_name='مناسبت\u200cها')),
                ('features', models.ManyToManyField(blank=True, related_name='products', to='catalog.productfeature', verbose_name='ویژگی\u200cها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('label', models.CharField(max_length=60, verbose_name='عنوان')),
                ('price_delta_rial', models.BigIntegerField(default=0, verbose_name='اختلاف قیمت (ریال)')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='توضیح')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'افزودنی',
                'verbose_name_plural': 'افزودنی\u200cها',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('label', models.CharField(max_length=60, verbose_name='عنوان')),
                ('price_delta_rial', models.BigIntegerField(default=0, verbose_name='اختلاف قیمت (ریال)')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'طعم',
                'verbose_name_plural': 'طعم\u200cها',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFlavorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('label', models.CharField(help_text='گلاب کاشان', max_length=60, verbose_name='نت')),
                ('weight', models.SmallIntegerField(default=50, help_text='عددی بین ۰ تا ۱۰۰ — عرض نوار در صفحه\u200cی محصول.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='شدت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_notes', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نت طعم',
                'verbose_name_plural': 'هرم طعم',
                'ordering': ('sort_order', '-weight'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('image', apps.common.fields.ImageField(upload_to=apps.common.upload.UploadTo('catalog/products'), verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, help_text='برای صفحه\u200cخوان و وقتی تصویر بالا نمی\u200cآید.', max_length=140, verbose_name='متن جایگزین')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ('-is_cover', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.SmallIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر بالاتر می\u200cآید.', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('label', models.CharField(max_length=60, verbose_name='عنوان')),
                ('price_delta_rial', models.BigIntegerField(default=0, verbose_name='اختلاف قیمت (ریال)')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('serves', models.CharField(blank=True, help_text='۸ تا ۱۰ نفر — حدود ۲ کیلو', max_length=60, verbose_name='تعداد نفرات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'اندازه',
                'verbose_name_plural': 'اندازه\u200cها',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=False, help_text='تا تأیید نشود در سایت دیده نمی\u200cشود.', verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'sort_order'], name='category_tree_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='product_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-sales_count'], name='product_best_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'price_rial'], name='product_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['-created_at'], name='product_live_new_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price_rial__gte', 0)), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productflavor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='product_one_default_flavor'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('product',), name='product_one_cover'),
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='product_one_default_size'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved', '-created_at'], name='review_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='review_one_per_user'),
        ),
    ]
