# Generated by Django 6.1.1 on 2026-09-23 09:51

import apps.common.fields
import apps.common.upload
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=apps.common.fields.ImageField(blank=True, max_dimension=1600, upload_to=apps.common.upload.UploadTo('catalog/categories'), verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=apps.common.fields.ImageField(max_dimension=1600, upload_to=apps.common.upload.UploadTo('catalog/gallery'), verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=apps.common.fields.ImageField(max_dimension=1600, upload_to=apps.common.upload.UploadTo('catalog/products'), verbose_name='تصویر'),
        ),
    ]
